version: '3.8'
services:
  dev1:
    container_name: appfirst
    build:
      context: .
      target: dev
    networks:
      - net11
    ports:
      - 5000:5000
  prod1:
    container_name: appsecond
    build:
      context: .
      target: prod
    networks:
      - net22
    ports:
      - 9000:9000
networks:
  net11:
  net22:
